### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by z3niths** [crazyfactory/docker-project-cli#14]
Should we have this feature ...

- Fake Apply migrations
- Reapply migrations
- List all migrations (DESC)
- Tool for create migrations (We store filename as a key in db_migrations table)
   - to confirm that we use same standard of migrations file name
   - easy to create migrations files

**Comment by wmathes** [comment]
Hmm that's up to the project isn't it? Meaning that if the project offer's a CLI for this, then dopr can relay to that.

in logistics (except for fake apply), this is possible already using
- `dopr migrations` quick info, returns 1 if migrations are missing
- `dopr migrations list` long (and ugly) list of all migrations and their states
- `dopr migrations apply` apply all unapplied migrations
