### ISSUE TITLE
should we add chain functionality?

### ISSUE THREAD

**Issue by wmathes** [crazyfactory/docker-project-cli#21]
imagine we have a `dopr setup` in ERP and it should run:
- `dopr up -d`
- `dopr npm run setup`

**Comment by adhocore** [comment]
shouldnt we use different command in `docker-project.json` like so: 
```json
{
    "up-run": {
      "command": ["@up -d", "@npm run setup"]
    },
    "host-cmd": {
      "service": "@host",
      "command": "ls -al"
    }
}
```
this requires supporting `@cmd` to reuse existing one.

additionally how about having a cmd that can run in host context? with `service` value as `@host` or `@none` or something

**Comment by wmathes** [comment]
allowing command to be array and then chain that sounds good :) 

running stuff in host is probably also useful (but should be a separate issue).

aliasing and calling other commands from within a command (chained or not) is also neat. Separate issue as well (and i actually expect some more refactoring for this to work as the whole construction logic isn't properly encapsulated currently)
