### ISSUE TITLE
Possibility to run commands on host context

### ISSUE THREAD

**Issue by adhocore** [crazyfactory/docker-project-cli#24]
Branched from #21

**Comment by wmathes** [comment]
in what situation would we need this? ^^

**Comment by adhocore** [comment]
it is spinoff of #21, it finds real usage when chaining is possible later. shop api would be needing it as well

**Comment by wmathes** [comment]
for within the container i can't think of a real use-case right now. Which use-case in shop-api are you talking about? ^^

**Comment by adhocore** [comment]
from within the container it is not even possible (or not neatly) to invoke host cmd and we won't even need it. when booting up the app solely using this tool, we might have to run some preliminary commands in the machine before we can `up` the container and proceed

**Comment by wmathes** [comment]
ah misread, my bad
