### ISSUE TITLE
annoying prompt for batch

### ISSUE THREAD

**Issue by wmathes** [crazyfactory/docker-project-cli#5]
when running logistics with `dopr up -d`, quitting the process will issue into a "terminate batch process (y/n)" being spawned by the overlaying batch-file. This is annoying, but sadly not trivial to circumvent.

when running with `dopr bash` everything works as expected as the stdio is fully piped to the tty behind it (which captures any ctrl+c inputs).

Using readline or responding to the 'data' event on the stdin works to some degree, but then passing on data to the child processes stdin fails, breaking interaction.

For now it's just annoying, but we should fix this some day.

### essential docs
https://nodejs.org/api/readline.html#readline_event_sigint
https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

**Comment by adhocore** [comment]
maybe something to look for @paibamboo ?

for me it was never an issue as i use ubuntu

**Comment by paibamboo** [comment]
Never annoying for me :)

**Comment by adhocore** [comment]
ok then lets close for now
